# Generated by Django 3.0.8 on 2021-07-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubromovement',
            name='movement',
        ),
    ]
