# Generated by Django 3.0.8 on 2021-08-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20210805_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrobalanceoperation',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='rubrobalanceoperation',
            name='agreementNameAg',
        ),
        migrations.AddField(
            model_name='rubrobalanceoperation',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Movement'),
        ),
    ]
