# Generated by Django 3.0.8 on 2021-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_rubroinform_rubroinformdetall'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubroinformdetall',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
