# Generated by Django 3.0.8 on 2021-12-01 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_rubroinformdetall_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typecontractdetail',
            old_name='activity',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='informdetall',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='rubroinformdetall',
            name='valor',
        ),
        migrations.AlterField(
            model_name='typecontract',
            name='digitsTC',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Detall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionInfD', models.CharField(max_length=100)),
                ('informDetall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.InformDetall')),
            ],
        ),
        migrations.AddField(
            model_name='rubroinformdetall',
            name='detall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Detall'),
        ),
    ]
