# Generated by Django 3.0.8 on 2021-12-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_auto_20211201_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='nameRubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Rubro'),
        ),
    ]
