# Generated by Django 3.0.8 on 2021-12-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_auto_20211201_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='nameRubro',
            field=models.BigIntegerField(null=True),
        ),
    ]
