# Generated by Django 3.0.8 on 2021-12-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_auto_20211201_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubromovement',
            name='nameRubro',
        ),
        migrations.AddField(
            model_name='rubromovement',
            name='namerubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Rubro'),
        ),
    ]
