# Generated by Django 3.0.8 on 2021-12-01 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_auto_20211201_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='namerubro',
            new_name='nameRubro',
        ),
    ]
