# Generated by Django 3.0.8 on 2021-12-02 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_auto_20211201_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubrobalanceoperation',
            old_name='namerubro',
            new_name='nameRubro',
        ),
    ]
