# Generated by Django 3.0.8 on 2021-12-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0016_auto_20211201_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
