# Generated by Django 3.0.8 on 2021-12-06 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0017_typedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='accountPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.AccountPeriod'),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='bussines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Bussines'),
        ),
    ]
