# Generated by Django 3.0.8 on 2021-12-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0018_auto_20211205_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typecontract',
            name='categoryTC',
        ),
        migrations.RemoveField(
            model_name='typecontract',
            name='digitsTC',
        ),
    ]
