# Generated by Django 3.0.8 on 2021-12-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0019_auto_20211219_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecontractdetail',
            name='digitstc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
