# Generated by Django 3.0.8 on 2021-12-19 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0020_typecontractdetail_digitstc'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeContractMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.Movement')),
                ('typeContractdetail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.TypeContractDetail')),
            ],
        ),
    ]
