# Generated by Django 3.0.8 on 2022-01-02 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0021_typecontractmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('activate', models.BooleanField()),
                ('accountPeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.AccountPeriod')),
            ],
        ),
    ]
