# Generated by Django 3.0.8 on 2022-01-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0022_closedperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedperiod',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
