# Generated by Django 3.0.8 on 2022-01-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0024_remove_origin_finaldateorigin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inform',
            name='digitI',
        ),
    ]
