# Generated by Django 3.0.8 on 2022-02-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0025_remove_inform_digiti'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
