# Generated by Django 3.0.8 on 2022-02-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0026_origin_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCPET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('dpto', models.BooleanField()),
                ('mpio', models.BooleanField()),
                ('guard', models.BooleanField()),
                ('ips', models.BooleanField()),
                ('particu', models.BooleanField()),
            ],
        ),
    ]
