# Generated by Django 3.0.8 on 2022-02-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0027_ccpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubro',
            name='ccpet',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
