# Generated by Django 3.0.8 on 2022-02-20 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0028_rubro_ccpet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccpet',
            name='accountPeriod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgets.AccountPeriod'),
        ),
    ]
