# Generated by Django 3.0.8 on 2022-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0031_auto_20220220_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='average',
            field=models.FloatField(),
        ),
    ]
