# Generated by Django 3.0.8 on 2022-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0032_auto_20220223_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccpet',
            name='dpto',
        ),
        migrations.RemoveField(
            model_name='ccpet',
            name='guard',
        ),
        migrations.RemoveField(
            model_name='ccpet',
            name='ips',
        ),
        migrations.RemoveField(
            model_name='ccpet',
            name='mpio',
        ),
        migrations.RemoveField(
            model_name='ccpet',
            name='particu',
        ),
    ]
